[package]
name = "aster"
version = "0.1.0"
authors = ["Christian Nyumbayire <chritchens@gmail.com>"]
repository = "https://github.com/chritchens/aster"
readme = "README.md"
keywords = ["development"]
license = "MIT OR Apache-2.0"
rust-version = "1.65"
edition = "2018"

[dependencies]
