[package]
name = "sophia"
version = "0.1.0"
authors = ["Christian Nyumbayire <chritchens@gmail.com>"]
repository = "https://github.com/chritchens/sophia"
readme = "README.md"
keywords = ["development"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
